use_frameworks!

platform :ios, '9.0'

target 'WeChatCustomerServiceLib_Example' do
  pod 'WeChatCustomerServiceLib', :path => '../'

  target 'WeChatCustomerServiceLib_Tests' do
    inherit! :search_paths

    
  end
end
